version: "3"

services:
  server:
    container_name: jeepunii-server
    image: avidian/jeepunii-server
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - database
      - queue
    networks:
      - net
    environment:
      PORT: 8000
      ENV: local
      KEY: abc
      DB_CONNECTION: postgres
      DB_HOST: jeepunii-db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      DB_NAME: jeepunii
      REDIS_HOST: jeepunii-queue
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      LOCATION_IQ_TOKEN: pk.3d277e20a9f72b0f3da1f69aa0aa313d
      SOCKET_DRIVER: redis
      STORAGE_ENGINE: local
  web:
    container_name: jeepunii-web
    image: avidian/jeepunii-web
    build: ./web
    volumes:
      - ./web:/var/www/html
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - net
  database:
    container_name: jeepunii-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: jeepunii
    volumes:
      - "jeepunii-database:/var/lib/postgresql/data"
    ports:
      - 2158:5432
    networks:
      - net
  queue:
    image: redis:latest
    container_name: jeepunii-queue
    restart: unless-stopped
    ports:
      - 8725:6379
    networks:
      - net
    volumes:
      - "jeepunii-redis:/data"
networks:
  net:
    internal: false
    driver: bridge

volumes:
  jeepunii-database:
    driver: local
  jeepunii-redis:
    driver: local
