export const routes = {
	LANDING: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	DASHBOARD: '/dashboard',
	USERS: '/users',
	JEEPS: '/jeeps',
	COOPERATIVES: '/cooperatives',
	SALES: '/sales',
	LOGS: '/logs',
	CHATS: '/chats',
	ROUTES: '/routes',
	SETTINGS: '/settings',
	DRIVERS: '/drivers',
	OWNERS: '/cooperative-owners',
	ADMINS: '/administrators',
	PASSENGERS: '/passengers',
};
